server:
  port: 8769
eureka:
  client:
    service-url:
      host: http://localhost:8761/eureka/
spring:
  application:
    name: server-gateway
zuul:
  routes:
    api-admin:
      path: /api-admin/**
      serviceId: service-admin
    api-order:
      path: /api-order/**
      serviceId: service-order
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
